"""Constants for BackupCheckup."""

from homeassistant.const import Platform

DOMAIN = "backup_checkup"
CONFIG_ENTRY_VERSION = 11
NAME = "BackupCheckup"
VERSION = "2.5.2"

PLATFORMS: tuple[Platform, ...] = (
    Platform.SENSOR,
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
)

DOCUMENTATION_URL = "https://github.com/jl0906/BackupCheckup"
TROUBLESHOOTING_URL = f"{DOCUMENTATION_URL}/blob/main/docs/troubleshooting.md"

CONF_MAX_AGE_DAYS = "max_age_days"
CONF_UPDATE_INTERVAL_MINUTES = "update_interval_minutes"
CONF_MINIMUM_BACKUP_SIZE_MB = "minimum_backup_size_mb"
CONF_MAXIMUM_SIZE_DROP_PERCENT = "maximum_size_drop_percent"
CONF_MINIMUM_REDUNDANT_LOCATIONS = "minimum_redundant_locations"
CONF_MONITORING_PROFILE = "monitoring_profile"  # Legacy schema key (<= 2.3.x)
CONF_RUNTIME_PROFILE = "runtime_profile"
CONF_MONITORING_POLICY = "monitoring_policy"
CONF_VERIFICATION_POLICY = "verification_policy"
CONF_ADAPTIVE_POLLING = "adaptive_polling"
CONF_ACTIVE_UPDATE_INTERVAL_MINUTES = "active_update_interval_minutes"
CONF_ERROR_BACKOFF_INTERVAL_MINUTES = "error_backoff_interval_minutes"
CONF_ADAPTIVE_ERROR_THRESHOLD = "adaptive_error_threshold"
CONF_PRESET_REVISION = "preset_revision"
CONF_HARDWARE_DETECTION = "hardware_detection"
CONF_SIZE_CHECK_MODE = "size_check_mode"
CONF_REPAIR_ISSUES_ENABLED = "repair_issues_enabled"
CONF_ANALYTICS_WINDOW_DAYS = "analytics_window_days"
CONF_AUTO_VERIFY_NEW_BACKUPS = "auto_verify_new_backups"
CONF_DATABASE_INTEGRITY_CHECK = "database_integrity_check"
CONF_NOTIFICATIONS_ENABLED = "notifications_enabled"
CONF_NOTIFICATION_TARGETS = "notification_targets"
CONF_NOTIFY_ON_RECOVERY = "notify_on_recovery"
CONF_ENTITY_MODE = "entity_mode"
CONF_MAX_VERIFICATION_SIZE_GB = "max_verification_size_gb"
CONF_MAX_EXPANDED_SIZE_GB = "max_expanded_size_gb"
CONF_VERIFICATION_TIMEOUT_MINUTES = "verification_timeout_minutes"
CONF_DATABASE_TIMEOUT_MINUTES = "database_timeout_minutes"
CONF_MANUAL_VERIFICATION_COOLDOWN_MINUTES = "manual_verification_cooldown_minutes"
CONF_EXPOSE_BACKUP_METADATA = "expose_backup_metadata"
CONF_SHOW_SIDEBAR_PANEL = "show_sidebar_panel"

# Legacy monitoring-profile values retained for migration.
PROFILE_STANDARD = "standard"
PROFILE_SECURE = "secure"
PROFILE_CUSTOM = "custom"
PROFILE_OPTIONS = [PROFILE_STANDARD, PROFILE_SECURE, PROFILE_CUSTOM]

RUNTIME_PROFILE_ENERGY_SAVING = "energy_saving"
RUNTIME_PROFILE_APPLIANCE = "home_assistant_appliance"
RUNTIME_PROFILE_PERFORMANCE = "performance"
RUNTIME_PROFILE_SERVER = "server"
RUNTIME_PROFILE_CUSTOM = "custom"
RUNTIME_PROFILE_LEGACY = "legacy_custom"
RUNTIME_PROFILE_OPTIONS = [
    RUNTIME_PROFILE_ENERGY_SAVING,
    RUNTIME_PROFILE_APPLIANCE,
    RUNTIME_PROFILE_PERFORMANCE,
    RUNTIME_PROFILE_SERVER,
    RUNTIME_PROFILE_CUSTOM,
]
RUNTIME_PROFILE_STORED_OPTIONS = [*RUNTIME_PROFILE_OPTIONS, RUNTIME_PROFILE_LEGACY]

MONITORING_POLICY_BALANCED = "balanced"
MONITORING_POLICY_STRICT = "strict"
MONITORING_POLICY_CUSTOM = "custom"
MONITORING_POLICY_OPTIONS = [
    MONITORING_POLICY_BALANCED,
    MONITORING_POLICY_STRICT,
    MONITORING_POLICY_CUSTOM,
]

VERIFICATION_POLICY_MANUAL = "manual"
VERIFICATION_POLICY_AUTOMATIC = "automatic"
VERIFICATION_POLICY_DEEP = "deep"
VERIFICATION_POLICY_CUSTOM = "custom"
VERIFICATION_POLICY_OPTIONS = [
    VERIFICATION_POLICY_MANUAL,
    VERIFICATION_POLICY_AUTOMATIC,
    VERIFICATION_POLICY_DEEP,
]
VERIFICATION_POLICY_STORED_OPTIONS = [
    *VERIFICATION_POLICY_OPTIONS,
    VERIFICATION_POLICY_CUSTOM,
]

PRESET_REVISION = 1
DEFAULT_RUNTIME_PROFILE = RUNTIME_PROFILE_APPLIANCE
DEFAULT_MONITORING_POLICY = MONITORING_POLICY_BALANCED
DEFAULT_VERIFICATION_POLICY = VERIFICATION_POLICY_MANUAL
DEFAULT_ADAPTIVE_POLLING = True
DEFAULT_ACTIVE_UPDATE_INTERVAL_MINUTES = 1
DEFAULT_ERROR_BACKOFF_INTERVAL_MINUTES = 30
DEFAULT_ADAPTIVE_ERROR_THRESHOLD = 3
DEFAULT_HARDWARE_DETECTION: dict[str, str] = {}

SIZE_CHECK_AUTO = "automatic"
SIZE_CHECK_FIXED = "fixed"
SIZE_CHECK_OFF = "disabled"
SIZE_CHECK_OPTIONS = [SIZE_CHECK_AUTO, SIZE_CHECK_FIXED, SIZE_CHECK_OFF]

DEFAULT_MONITORING_PROFILE = PROFILE_STANDARD
DEFAULT_SIZE_CHECK_MODE = SIZE_CHECK_AUTO
DEFAULT_REPAIR_ISSUES_ENABLED = True
DEFAULT_ANALYTICS_WINDOW_DAYS = 30
DEFAULT_AUTO_VERIFY_NEW_BACKUPS = False
DEFAULT_DATABASE_INTEGRITY_CHECK = False
DEFAULT_NOTIFICATIONS_ENABLED = False
DEFAULT_NOTIFICATION_TARGETS: list[str] = []
DEFAULT_NOTIFY_ON_RECOVERY = True
DEFAULT_MAX_VERIFICATION_SIZE_GB = 50
DEFAULT_MAX_EXPANDED_SIZE_GB = 250
DEFAULT_VERIFICATION_TIMEOUT_MINUTES = 60
DEFAULT_DATABASE_TIMEOUT_MINUTES = 15
DEFAULT_MANUAL_VERIFICATION_COOLDOWN_MINUTES = 15
DEFAULT_EXPOSE_BACKUP_METADATA = False
DEFAULT_SHOW_SIDEBAR_PANEL = False

BACKUP_PURPOSE_AUTOMATIC = "automatic"
BACKUP_PURPOSE_MANUAL = "manual"
BACKUP_PURPOSE_APP_UPDATE = "app_update"
BACKUP_PURPOSE_OPTIONS = [
    BACKUP_PURPOSE_AUTOMATIC,
    BACKUP_PURPOSE_MANUAL,
    BACKUP_PURPOSE_APP_UPDATE,
]
APP_UPDATE_METADATA_KEY = "supervisor.addon_update"

ENTITY_MODE_STANDARD = "standard"
ENTITY_MODE_EXPERT = "expert"
ENTITY_MODE_OPTIONS = [ENTITY_MODE_STANDARD, ENTITY_MODE_EXPERT]
DEFAULT_ENTITY_MODE = ENTITY_MODE_STANDARD

DEFAULT_MAX_AGE_DAYS = 4
DEFAULT_UPDATE_INTERVAL_MINUTES = 10
DEFAULT_MINIMUM_BACKUP_SIZE_MB = 1
DEFAULT_MAXIMUM_SIZE_DROP_PERCENT = 50
DEFAULT_MINIMUM_REDUNDANT_LOCATIONS = 1

MIN_MAX_AGE_DAYS = 1
MAX_MAX_AGE_DAYS = 365
MIN_UPDATE_INTERVAL_MINUTES = 1
MAX_UPDATE_INTERVAL_MINUTES = 60
MIN_ACTIVE_UPDATE_INTERVAL_MINUTES = 1
MAX_ACTIVE_UPDATE_INTERVAL_MINUTES = 15
MIN_ERROR_BACKOFF_INTERVAL_MINUTES = 5
MAX_ERROR_BACKOFF_INTERVAL_MINUTES = 240
MIN_ADAPTIVE_ERROR_THRESHOLD = 1
MAX_ADAPTIVE_ERROR_THRESHOLD = 10
MIN_MINIMUM_BACKUP_SIZE_MB = 0
MAX_MINIMUM_BACKUP_SIZE_MB = 102400
MIN_MAXIMUM_SIZE_DROP_PERCENT = 0
MAX_MAXIMUM_SIZE_DROP_PERCENT = 100
MIN_REDUNDANT_LOCATIONS = 1
MAX_REDUNDANT_LOCATIONS = 20
MIN_ANALYTICS_WINDOW_DAYS = 7
MAX_ANALYTICS_WINDOW_DAYS = 365
MIN_MAX_VERIFICATION_SIZE_GB = 1
MAX_MAX_VERIFICATION_SIZE_GB = 2048
MIN_MAX_EXPANDED_SIZE_GB = 1
MAX_MAX_EXPANDED_SIZE_GB = 8192
MIN_VERIFICATION_TIMEOUT_MINUTES = 1
MAX_VERIFICATION_TIMEOUT_MINUTES = 1440
MIN_DATABASE_TIMEOUT_MINUTES = 1
MAX_DATABASE_TIMEOUT_MINUTES = 1440
MIN_MANUAL_VERIFICATION_COOLDOWN_MINUTES = 0
MAX_MANUAL_VERIFICATION_COOLDOWN_MINUTES = 1440

MAX_ARCHIVE_MEMBERS = 1_000_000
MAX_BACKUP_METADATA_BYTES = 2 * 1024 * 1024
MIN_FREE_SPACE_RESERVE_BYTES = 1024 * 1024 * 1024
STALE_TEMP_DIRECTORY_AGE_HOURS = 24
SERVICE_VERIFY_LATEST_BACKUP = "verify_latest_backup"
SERVICE_REFRESH = "refresh"
SERVICE_TEST_NOTIFICATION = "test_notification"

STATUS_OK = "ok"
STATUS_NO_BACKUPS = "no_backups"
STATUS_AUTOMATIC_BACKUP_OVERDUE = "automatic_backup_overdue"
STATUS_BACKUP_STALE = "backup_stale"
STATUS_AUTOMATIC_BACKUP_FAILED = "automatic_backup_failed"
STATUS_SCHEDULE_MISSING = "schedule_missing"
STATUS_SCHEDULE_OVERDUE = "schedule_overdue"
STATUS_MANAGER_UNAVAILABLE = "manager_unavailable"
STATUS_STORAGE_ERROR = "storage_error"
STATUS_BACKUP_SIZE_SUSPICIOUS = "backup_size_suspicious"
STATUS_BACKUP_INCOMPLETE = "backup_incomplete"
STATUS_BACKUP_NOT_REDUNDANT = "backup_not_redundant"
STATUS_BACKUP_INTEGRITY_FAILED = "backup_integrity_failed"
STATUS_BACKUP_INTEGRITY_WARNING = "backup_integrity_warning"
STATUS_BACKUP_CHECKSUM_CHANGED = "backup_checksum_changed"

STATUS_OPTIONS = [
    STATUS_OK,
    STATUS_NO_BACKUPS,
    STATUS_AUTOMATIC_BACKUP_OVERDUE,
    STATUS_BACKUP_STALE,
    STATUS_AUTOMATIC_BACKUP_FAILED,
    STATUS_SCHEDULE_MISSING,
    STATUS_SCHEDULE_OVERDUE,
    STATUS_MANAGER_UNAVAILABLE,
    STATUS_STORAGE_ERROR,
    STATUS_BACKUP_SIZE_SUSPICIOUS,
    STATUS_BACKUP_INCOMPLETE,
    STATUS_BACKUP_NOT_REDUNDANT,
    STATUS_BACKUP_INTEGRITY_FAILED,
    STATUS_BACKUP_INTEGRITY_WARNING,
    STATUS_BACKUP_CHECKSUM_CHANGED,
]

BACKUP_RESULT_COMPLETE = "complete"
BACKUP_RESULT_PARTIAL = "partial"
BACKUP_RESULT_UNKNOWN = "unknown"
BACKUP_RESULT_OPTIONS = [
    BACKUP_RESULT_COMPLETE,
    BACKUP_RESULT_PARTIAL,
    BACKUP_RESULT_UNKNOWN,
]

RECOMMENDATION_NONE = "none"
RECOMMENDATION_CREATE_BACKUP = "create_backup"
RECOMMENDATION_CHECK_SCHEDULE = "check_schedule"
RECOMMENDATION_CHECK_STORAGE = "check_storage"
RECOMMENDATION_CHECK_BACKUP_CONTENTS = "check_backup_contents"
RECOMMENDATION_CHECK_BACKUP_SIZE = "check_backup_size"
RECOMMENDATION_ADD_STORAGE_LOCATION = "add_storage_location"
RECOMMENDATION_CHECK_BACKUP_SYSTEM = "check_backup_system"
RECOMMENDATION_REPLACE_BACKUP = "replace_backup"
RECOMMENDATION_OPTIONS = [
    RECOMMENDATION_NONE,
    RECOMMENDATION_CREATE_BACKUP,
    RECOMMENDATION_CHECK_SCHEDULE,
    RECOMMENDATION_CHECK_STORAGE,
    RECOMMENDATION_CHECK_BACKUP_CONTENTS,
    RECOMMENDATION_CHECK_BACKUP_SIZE,
    RECOMMENDATION_ADD_STORAGE_LOCATION,
    RECOMMENDATION_CHECK_BACKUP_SYSTEM,
    RECOMMENDATION_REPLACE_BACKUP,
]

HEALTH_RATING_EXCELLENT = "excellent"
HEALTH_RATING_GOOD = "good"
HEALTH_RATING_WARNING = "warning"
HEALTH_RATING_CRITICAL = "critical"
HEALTH_SCORE_VERSION = 2
HEALTH_RATING_OPTIONS = [
    HEALTH_RATING_EXCELLENT,
    HEALTH_RATING_GOOD,
    HEALTH_RATING_WARNING,
    HEALTH_RATING_CRITICAL,
]

SIZE_TREND_INCREASING = "increasing"
SIZE_TREND_STABLE = "stable"
SIZE_TREND_DECREASING = "decreasing"
SIZE_TREND_INSUFFICIENT_DATA = "insufficient_data"
SIZE_TREND_OPTIONS = [
    SIZE_TREND_INCREASING,
    SIZE_TREND_STABLE,
    SIZE_TREND_DECREASING,
    SIZE_TREND_INSUFFICIENT_DATA,
]


INTEGRITY_STATUS_NOT_CHECKED = "not_checked"
INTEGRITY_STATUS_CHECKING = "checking"
INTEGRITY_STATUS_VALID = "valid"
INTEGRITY_STATUS_VALID_WITH_WARNINGS = "valid_with_warnings"
INTEGRITY_STATUS_CORRUPT = "corrupt"
INTEGRITY_STATUS_UNREADABLE = "unreadable"
INTEGRITY_STATUS_PASSWORD_REQUIRED = "password_required"  # nosec B105
INTEGRITY_STATUS_ABORTED = "aborted"
INTEGRITY_STATUS_INTERNAL_ERROR = "internal_error"
INTEGRITY_STATUS_OPTIONS = [
    INTEGRITY_STATUS_NOT_CHECKED,
    INTEGRITY_STATUS_CHECKING,
    INTEGRITY_STATUS_VALID,
    INTEGRITY_STATUS_VALID_WITH_WARNINGS,
    INTEGRITY_STATUS_CORRUPT,
    INTEGRITY_STATUS_UNREADABLE,
    INTEGRITY_STATUS_PASSWORD_REQUIRED,
    INTEGRITY_STATUS_ABORTED,
    INTEGRITY_STATUS_INTERNAL_ERROR,
]

INTEGRITY_DATABASE_NOT_CHECKED = "not_checked"
INTEGRITY_DATABASE_PASSED = "passed"
INTEGRITY_DATABASE_FAILED = "failed"
INTEGRITY_DATABASE_NOT_FOUND = "not_found"
INTEGRITY_DATABASE_NOT_APPLICABLE = "not_applicable"
INTEGRITY_DATABASE_OPTIONS = [
    INTEGRITY_DATABASE_NOT_CHECKED,
    INTEGRITY_DATABASE_PASSED,
    INTEGRITY_DATABASE_FAILED,
    INTEGRITY_DATABASE_NOT_FOUND,
    INTEGRITY_DATABASE_NOT_APPLICABLE,
]

CORE_BACKUP_MANAGER_STATE = "sensor.backup_backup_manager_state"
CORE_LAST_AUTOMATIC_ATTEMPT = "sensor.backup_last_attempted_automatic_backup"
CORE_LAST_SUCCESSFUL_AUTOMATIC_BACKUP = "sensor.backup_last_successful_automatic_backup"
CORE_NEXT_AUTOMATIC_BACKUP = "sensor.backup_next_scheduled_automatic_backup"
CORE_AUTOMATIC_BACKUP_EVENT = "event.backup_automatic_backup"

REPAIR_ISSUE_IDS = (
    "no_backup",
    "backup_stale",
    "automatic_backup_overdue",
    "automatic_backup_failed",
    "automatic_schedule_missing",
    "automatic_schedule_overdue",
    "manager_unavailable",
    "storage_error",
    "backup_size_suspicious",
    "latest_backup_incomplete",
    "backup_not_redundant",
    "required_location_missing",
    "backup_integrity_failed",
    "backup_integrity_warning",
    "backup_checksum_changed",
    "temporary_cleanup_failed",
    "storage_data_invalid_integrity",
    "storage_data_invalid_history",
    "storage_data_invalid_notifications",
)
