"""Constants for BackupCheckup."""

from homeassistant.const import Platform

DOMAIN = "backup_checkup"
NAME = "BackupCheckup"
VERSION = "1.2.0"

PLATFORMS: tuple[Platform, ...] = (Platform.SENSOR, Platform.BINARY_SENSOR)

CONF_MAX_AGE_DAYS = "max_age_days"
CONF_UPDATE_INTERVAL_MINUTES = "update_interval_minutes"
CONF_MINIMUM_BACKUP_SIZE_MB = "minimum_backup_size_mb"
CONF_MAXIMUM_SIZE_DROP_PERCENT = "maximum_size_drop_percent"
CONF_MINIMUM_REDUNDANT_LOCATIONS = "minimum_redundant_locations"

DEFAULT_MAX_AGE_DAYS = 4
DEFAULT_UPDATE_INTERVAL_MINUTES = 1
DEFAULT_MINIMUM_BACKUP_SIZE_MB = 1
DEFAULT_MAXIMUM_SIZE_DROP_PERCENT = 50
DEFAULT_MINIMUM_REDUNDANT_LOCATIONS = 2
MIN_MAX_AGE_DAYS = 1
MAX_MAX_AGE_DAYS = 365
MIN_UPDATE_INTERVAL_MINUTES = 1
MAX_UPDATE_INTERVAL_MINUTES = 60
MIN_MINIMUM_BACKUP_SIZE_MB = 0
MAX_MINIMUM_BACKUP_SIZE_MB = 102400
MIN_MAXIMUM_SIZE_DROP_PERCENT = 0
MAX_MAXIMUM_SIZE_DROP_PERCENT = 100
MIN_REDUNDANT_LOCATIONS = 1
MAX_REDUNDANT_LOCATIONS = 20

STATUS_OK = "ok"
STATUS_NO_BACKUPS = "no_backups"
STATUS_AUTOMATIC_BACKUP_OVERDUE = "automatic_backup_overdue"
STATUS_BACKUP_STALE = "backup_stale"
STATUS_AUTOMATIC_BACKUP_FAILED = "automatic_backup_failed"
STATUS_SCHEDULE_MISSING = "schedule_missing"
STATUS_SCHEDULE_OVERDUE = "schedule_overdue"
STATUS_MANAGER_UNAVAILABLE = "manager_unavailable"
STATUS_STORAGE_ERROR = "storage_error"
STATUS_BACKUP_SIZE_SUSPICIOUS = "backup_size_suspicious"
STATUS_BACKUP_INCOMPLETE = "backup_incomplete"
STATUS_BACKUP_NOT_REDUNDANT = "backup_not_redundant"

STATUS_OPTIONS = [
    STATUS_OK,
    STATUS_NO_BACKUPS,
    STATUS_AUTOMATIC_BACKUP_OVERDUE,
    STATUS_BACKUP_STALE,
    STATUS_AUTOMATIC_BACKUP_FAILED,
    STATUS_SCHEDULE_MISSING,
    STATUS_SCHEDULE_OVERDUE,
    STATUS_MANAGER_UNAVAILABLE,
    STATUS_STORAGE_ERROR,
    STATUS_BACKUP_SIZE_SUSPICIOUS,
    STATUS_BACKUP_INCOMPLETE,
    STATUS_BACKUP_NOT_REDUNDANT,
]

BACKUP_RESULT_COMPLETE = "complete"
BACKUP_RESULT_PARTIAL = "partial"
BACKUP_RESULT_UNKNOWN = "unknown"
BACKUP_RESULT_OPTIONS = [
    BACKUP_RESULT_COMPLETE,
    BACKUP_RESULT_PARTIAL,
    BACKUP_RESULT_UNKNOWN,
]

CORE_BACKUP_MANAGER_STATE = "sensor.backup_backup_manager_state"
CORE_LAST_AUTOMATIC_ATTEMPT = "sensor.backup_last_attempted_automatic_backup"
CORE_LAST_SUCCESSFUL_AUTOMATIC_BACKUP = "sensor.backup_last_successful_automatic_backup"
CORE_NEXT_AUTOMATIC_BACKUP = "sensor.backup_next_scheduled_automatic_backup"
