"""Constants for BackupCheckup."""

from homeassistant.const import Platform

DOMAIN = "backup_checkup"
NAME = "BackupCheckup"
VERSION = "1.5.0"

PLATFORMS: tuple[Platform, ...] = (
    Platform.SENSOR,
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
)

DOCUMENTATION_URL = "https://github.com/jl0906/BackupCheckup"
TROUBLESHOOTING_URL = f"{DOCUMENTATION_URL}#troubleshooting"

CONF_MAX_AGE_DAYS = "max_age_days"
CONF_UPDATE_INTERVAL_MINUTES = "update_interval_minutes"
CONF_MINIMUM_BACKUP_SIZE_MB = "minimum_backup_size_mb"
CONF_MAXIMUM_SIZE_DROP_PERCENT = "maximum_size_drop_percent"
CONF_MINIMUM_REDUNDANT_LOCATIONS = "minimum_redundant_locations"
CONF_MONITORING_PROFILE = "monitoring_profile"
CONF_SIZE_CHECK_MODE = "size_check_mode"
CONF_REPAIR_ISSUES_ENABLED = "repair_issues_enabled"
CONF_ANALYTICS_WINDOW_DAYS = "analytics_window_days"

PROFILE_STANDARD = "standard"
PROFILE_SECURE = "secure"
PROFILE_CUSTOM = "custom"
PROFILE_OPTIONS = [PROFILE_STANDARD, PROFILE_SECURE, PROFILE_CUSTOM]

SIZE_CHECK_AUTO = "automatic"
SIZE_CHECK_FIXED = "fixed"
SIZE_CHECK_OFF = "disabled"
SIZE_CHECK_OPTIONS = [SIZE_CHECK_AUTO, SIZE_CHECK_FIXED, SIZE_CHECK_OFF]

DEFAULT_MONITORING_PROFILE = PROFILE_STANDARD
DEFAULT_SIZE_CHECK_MODE = SIZE_CHECK_AUTO
DEFAULT_REPAIR_ISSUES_ENABLED = True
DEFAULT_ANALYTICS_WINDOW_DAYS = 30

DEFAULT_MAX_AGE_DAYS = 4
DEFAULT_UPDATE_INTERVAL_MINUTES = 5
DEFAULT_MINIMUM_BACKUP_SIZE_MB = 1
DEFAULT_MAXIMUM_SIZE_DROP_PERCENT = 50
DEFAULT_MINIMUM_REDUNDANT_LOCATIONS = 1

MIN_MAX_AGE_DAYS = 1
MAX_MAX_AGE_DAYS = 365
MIN_UPDATE_INTERVAL_MINUTES = 1
MAX_UPDATE_INTERVAL_MINUTES = 60
MIN_MINIMUM_BACKUP_SIZE_MB = 0
MAX_MINIMUM_BACKUP_SIZE_MB = 102400
MIN_MAXIMUM_SIZE_DROP_PERCENT = 0
MAX_MAXIMUM_SIZE_DROP_PERCENT = 100
MIN_REDUNDANT_LOCATIONS = 1
MAX_REDUNDANT_LOCATIONS = 20
MIN_ANALYTICS_WINDOW_DAYS = 7
MAX_ANALYTICS_WINDOW_DAYS = 365

STATUS_OK = "ok"
STATUS_NO_BACKUPS = "no_backups"
STATUS_AUTOMATIC_BACKUP_OVERDUE = "automatic_backup_overdue"
STATUS_BACKUP_STALE = "backup_stale"
STATUS_AUTOMATIC_BACKUP_FAILED = "automatic_backup_failed"
STATUS_SCHEDULE_MISSING = "schedule_missing"
STATUS_SCHEDULE_OVERDUE = "schedule_overdue"
STATUS_MANAGER_UNAVAILABLE = "manager_unavailable"
STATUS_STORAGE_ERROR = "storage_error"
STATUS_BACKUP_SIZE_SUSPICIOUS = "backup_size_suspicious"
STATUS_BACKUP_INCOMPLETE = "backup_incomplete"
STATUS_BACKUP_NOT_REDUNDANT = "backup_not_redundant"

STATUS_OPTIONS = [
    STATUS_OK,
    STATUS_NO_BACKUPS,
    STATUS_AUTOMATIC_BACKUP_OVERDUE,
    STATUS_BACKUP_STALE,
    STATUS_AUTOMATIC_BACKUP_FAILED,
    STATUS_SCHEDULE_MISSING,
    STATUS_SCHEDULE_OVERDUE,
    STATUS_MANAGER_UNAVAILABLE,
    STATUS_STORAGE_ERROR,
    STATUS_BACKUP_SIZE_SUSPICIOUS,
    STATUS_BACKUP_INCOMPLETE,
    STATUS_BACKUP_NOT_REDUNDANT,
]

BACKUP_RESULT_COMPLETE = "complete"
BACKUP_RESULT_PARTIAL = "partial"
BACKUP_RESULT_UNKNOWN = "unknown"
BACKUP_RESULT_OPTIONS = [
    BACKUP_RESULT_COMPLETE,
    BACKUP_RESULT_PARTIAL,
    BACKUP_RESULT_UNKNOWN,
]

RECOMMENDATION_NONE = "none"
RECOMMENDATION_CREATE_BACKUP = "create_backup"
RECOMMENDATION_CHECK_SCHEDULE = "check_schedule"
RECOMMENDATION_CHECK_STORAGE = "check_storage"
RECOMMENDATION_CHECK_BACKUP_CONTENTS = "check_backup_contents"
RECOMMENDATION_CHECK_BACKUP_SIZE = "check_backup_size"
RECOMMENDATION_ADD_STORAGE_LOCATION = "add_storage_location"
RECOMMENDATION_CHECK_BACKUP_SYSTEM = "check_backup_system"
RECOMMENDATION_OPTIONS = [
    RECOMMENDATION_NONE,
    RECOMMENDATION_CREATE_BACKUP,
    RECOMMENDATION_CHECK_SCHEDULE,
    RECOMMENDATION_CHECK_STORAGE,
    RECOMMENDATION_CHECK_BACKUP_CONTENTS,
    RECOMMENDATION_CHECK_BACKUP_SIZE,
    RECOMMENDATION_ADD_STORAGE_LOCATION,
    RECOMMENDATION_CHECK_BACKUP_SYSTEM,
]

HEALTH_RATING_EXCELLENT = "excellent"
HEALTH_RATING_GOOD = "good"
HEALTH_RATING_WARNING = "warning"
HEALTH_RATING_CRITICAL = "critical"
HEALTH_RATING_OPTIONS = [
    HEALTH_RATING_EXCELLENT,
    HEALTH_RATING_GOOD,
    HEALTH_RATING_WARNING,
    HEALTH_RATING_CRITICAL,
]

SIZE_TREND_INCREASING = "increasing"
SIZE_TREND_STABLE = "stable"
SIZE_TREND_DECREASING = "decreasing"
SIZE_TREND_INSUFFICIENT_DATA = "insufficient_data"
SIZE_TREND_OPTIONS = [
    SIZE_TREND_INCREASING,
    SIZE_TREND_STABLE,
    SIZE_TREND_DECREASING,
    SIZE_TREND_INSUFFICIENT_DATA,
]

CORE_BACKUP_MANAGER_STATE = "sensor.backup_backup_manager_state"
CORE_LAST_AUTOMATIC_ATTEMPT = "sensor.backup_last_attempted_automatic_backup"
CORE_LAST_SUCCESSFUL_AUTOMATIC_BACKUP = "sensor.backup_last_successful_automatic_backup"
CORE_NEXT_AUTOMATIC_BACKUP = "sensor.backup_next_scheduled_automatic_backup"

REPAIR_ISSUE_IDS = (
    "no_backup",
    "backup_stale",
    "automatic_backup_overdue",
    "automatic_backup_failed",
    "automatic_schedule_missing",
    "automatic_schedule_overdue",
    "manager_unavailable",
    "storage_error",
    "backup_size_suspicious",
    "latest_backup_incomplete",
    "backup_not_redundant",
)
